"""Aggregate safe, stage-oriented timing data from an Agent event trace.

The event stream already carries timestamps and per-phase elapsed values.  This
module only derives counters and intervals from those events; it never stores
prompt text, model reasoning, tool arguments, or provider credentials.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, Iterable, Mapping, Sequence


_LIFECYCLE_TYPE = "AgentLifecycleTrace"
_LIFECYCLE_VERSION = 1
_TERMINAL_EVENTS = frozenset({"AgentCompleted", "AgentError", "AgentCancelled"})
_OUTPUT_EVENTS = frozenset({"TextChunk", "ReasoningChunk"})
_SUBSTANTIVE_EVENTS = frozenset(
    {
        "TextChunk",
        "ReasoningChunk",
        "ProviderFirstByte",
        "FirstByte",
        "ModelCompleted",
        "ToolStart",
        "ToolStarted",
        "ToolDone",
    }
)


def _as_mapping(value: Any) -> Mapping[str, Any]:
    return value if isinstance(value, Mapping) else {}


def _event_name(event: Mapping[str, Any]) -> str:
    return str(event.get("event") or event.get("type") or "").strip()


def _event_data(event: Mapping[str, Any]) -> Mapping[str, Any]:
    data = event.get("data")
    return _as_mapping(data) if isinstance(data, Mapping) else event


def _value(event: Mapping[str, Any], key: str, default: Any = None) -> Any:
    data = _event_data(event)
    if key in data:
        return data.get(key)
    return event.get(key, default)


def _parse_timestamp(value: Any) -> datetime | None:
    text = str(value or "").strip()
    if not text:
        return None
    try:
        parsed = datetime.fromisoformat(text.replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed


def _event_timestamp(event: Mapping[str, Any]) -> datetime | None:
    # ``timestamp`` is generated by the backend trace writer.  Acceptance
    # clients may additionally attach ``observedAt``; use it only when the
    # server timestamp is absent.
    return _parse_timestamp(event.get("timestamp")) or _parse_timestamp(event.get("observedAt"))


def _payload_timestamp(event: Mapping[str, Any], key: str) -> datetime | None:
    return _parse_timestamp(_value(event, key))


def _format_timestamp(value: datetime | None) -> str:
    return value.astimezone(timezone.utc).isoformat() if value is not None else ""


def _duration_ms(start: datetime | None, end: datetime | None) -> int:
    if start is None or end is None:
        return 0
    return max(0, int(round((end - start).total_seconds() * 1000)))


def _nonnegative_int(value: Any) -> int:
    try:
        return max(0, int(value or 0))
    except (TypeError, ValueError):
        return 0


def _usage(payload: Mapping[str, Any]) -> Mapping[str, Any]:
    value = payload.get("usage")
    return _as_mapping(value) if isinstance(value, Mapping) else {}


def _usage_value(usage: Mapping[str, Any], *keys: str) -> int:
    for key in keys:
        if usage.get(key) is not None:
            return _nonnegative_int(usage.get(key))
    return 0


def _is_model_start(event: Mapping[str, Any]) -> bool:
    name = _event_name(event)
    if name == "ModelStarted":
        return True
    if name != "TurnPhase":
        return False
    return (
        str(_value(event, "phase") or "").strip() == "model"
        and str(_value(event, "status") or "").strip().lower() == "running"
    )


def _provider_stream_phase(event: Mapping[str, Any]) -> str:
    if _event_name(event) != "ProviderStream":
        return ""
    return str(_value(event, "phase") or "").strip()


def _first_provider_stream_event(
    events: Sequence[Mapping[str, Any]],
    phase: str,
    *,
    start: int = 0,
    end: int | None = None,
) -> tuple[int, Mapping[str, Any]] | None:
    limit = len(events) if end is None else min(len(events), end)
    for index in range(max(0, start), limit):
        event = events[index]
        if _provider_stream_phase(event) == phase:
            return index, event
    return None


def _provider_attempt_records(events: Sequence[Mapping[str, Any]]) -> list[Dict[str, Any]]:
    attempts: dict[int, Dict[str, Any]] = {}
    for event in events:
        phase = _provider_stream_phase(event)
        if not phase:
            continue
        attempt = max(1, _nonnegative_int(_value(event, "attempt")))
        record = attempts.setdefault(
            attempt,
            {
                "attempt": attempt,
                "requestBytes": 0,
                "responseBytes": 0,
                "wireMaxOutputTokens": 0,
                "wireParallelToolCalls": None,
                "httpStatus": 0,
                "responseHeadMs": 0,
                "firstByteMs": 0,
                "firstEventMs": 0,
                "lastObservedMs": 0,
                "durationMs": 0,
                "completed": False,
            },
        )
        record["requestBytes"] = max(
            _nonnegative_int(record.get("requestBytes")),
            _nonnegative_int(_value(event, "requestBytes")),
        )
        record["responseBytes"] = max(
            _nonnegative_int(record.get("responseBytes")),
            _nonnegative_int(_value(event, "responseBytes")),
        )
        record["wireMaxOutputTokens"] = max(
            _nonnegative_int(record.get("wireMaxOutputTokens")),
            _nonnegative_int(_value(event, "maxOutputTokens")),
        )
        parallel_tool_calls = _value(event, "parallelToolCalls")
        if isinstance(parallel_tool_calls, bool):
            record["wireParallelToolCalls"] = parallel_tool_calls
        record["httpStatus"] = max(
            _nonnegative_int(record.get("httpStatus")),
            _nonnegative_int(_value(event, "httpStatus")),
        )
        elapsed = _nonnegative_int(_value(event, "elapsedMs"))
        record["lastObservedMs"] = max(
            _nonnegative_int(record.get("lastObservedMs")),
            elapsed,
        )
        if phase == "response_head":
            record["responseHeadMs"] = elapsed
        elif phase == "first_byte":
            record["firstByteMs"] = elapsed
        elif phase == "first_event":
            record["firstEventMs"] = elapsed
        elif phase == "completed":
            record["durationMs"] = elapsed
            record["completed"] = True
    return [attempts[key] for key in sorted(attempts)]


def _first_event(
    events: Sequence[Mapping[str, Any]],
    names: Iterable[str],
    *,
    start: int = 0,
    end: int | None = None,
) -> tuple[int, Mapping[str, Any]] | None:
    wanted = set(names)
    limit = len(events) if end is None else min(len(events), end)
    for index in range(max(0, start), limit):
        if _event_name(events[index]) in wanted:
            return index, events[index]
    return None


def _round_records(events: Sequence[Mapping[str, Any]], request_started: datetime | None) -> list[Dict[str, Any]]:
    starts: list[tuple[int, Mapping[str, Any]]] = [
        (index, event)
        for index, event in enumerate(events)
        if _is_model_start(event)
    ]
    completions: list[tuple[int, Mapping[str, Any]]] = [
        (index, event)
        for index, event in enumerate(events)
        if _event_name(event) == "ModelCompleted"
    ]
    records: list[Dict[str, Any]] = []
    used_starts: set[int] = set()
    for completion_index, completion in completions:
        completion_round = _nonnegative_int(_value(completion, "round"))
        candidate: tuple[int, Mapping[str, Any]] | None = None
        # Prefer a matching round number, then the most recent unmatched start.
        for start_index, start in reversed(starts):
            if start_index >= completion_index or start_index in used_starts:
                continue
            start_round = _nonnegative_int(_value(start, "round") or _value(start, "current"))
            if completion_round and start_round == completion_round:
                candidate = (start_index, start)
                break
            if candidate is None:
                candidate = (start_index, start)
        if candidate is not None:
            start_index, start = candidate
            used_starts.add(start_index)
            started_at = _payload_timestamp(start, "startedAt") or _event_timestamp(start) or request_started
        else:
            start_index = 0
            started_at = _event_timestamp(completion) or request_started
        completed_at = _event_timestamp(completion)
        raw_first_byte = _first_provider_stream_event(
            events,
            "first_byte",
            start=start_index,
            end=completion_index + 1,
        )
        first_byte = raw_first_byte or _first_event(
            events,
            {
                "ProviderFirstByte",
                "FirstByte",
                "ReasoningChunk",
                "TextChunk",
                "ToolStart",
                "ToolStarted",
                "ModelCompleted",
            },
            start=start_index,
            end=completion_index + 1,
        )
        output_at = first_byte[1] if first_byte else None
        output_time = _event_timestamp(output_at) if output_at is not None else None
        next_start = next(
            (candidate_index for candidate_index, _candidate in starts if candidate_index > completion_index),
            len(events),
        )
        # The bridge emits ToolStart/ToolDone after ModelCompleted.  Keep
        # those events in the round that produced the tool request; the next
        # model start is the boundary for the following round.
        round_events = events[start_index:next_start]
        round_tools = sum(1 for item in round_events if _event_name(item) == "ToolDone")
        round_retries = sum(
            1 for item in round_events if _event_name(item) in {"ConnectionRetry", "ProviderRetry"}
        )
        payload = _event_data(completion)
        usage = _usage(payload)
        provider_attempts = _provider_attempt_records(events[start_index : completion_index + 1])
        completed_attempt = next(
            (item for item in reversed(provider_attempts) if bool(item.get("completed"))),
            provider_attempts[-1] if provider_attempts else {},
        )
        records.append(
            {
                "round": completion_round or len(records) + 1,
                "status": "completed",
                "startedAt": _format_timestamp(started_at),
                "firstByteAt": _format_timestamp(output_time),
                "completedAt": _format_timestamp(completed_at),
                "timeToFirstByteMs": _duration_ms(started_at, output_time),
                "firstByteSource": (
                    "provider_raw_stream" if raw_first_byte is not None else "decoded_event_fallback"
                ),
                "durationMs": _duration_ms(started_at, completed_at),
                "toolCalls": round_tools,
                "retryCount": round_retries,
                "responseModel": str(payload.get("responseModel") or ""),
                "finishReason": str(payload.get("finishReason") or ""),
                "nativeReasoning": bool(payload.get("nativeReasoning")),
                "inputTokens": _usage_value(usage, "input_tokens", "prompt_tokens", "inputTokens"),
                "cachedInputTokens": _usage_value(
                    usage,
                    "cached_input_tokens",
                    "cache_read_input_tokens",
                    "cachedInputTokens",
                ),
                "outputTokens": _usage_value(usage, "output_tokens", "completion_tokens", "outputTokens"),
                "reasoningTokens": _usage_value(usage, "reasoning_tokens", "reasoningTokens"),
                "providerResponseHeadMs": _nonnegative_int(completed_attempt.get("responseHeadMs")),
                "providerFirstByteMs": _nonnegative_int(completed_attempt.get("firstByteMs")),
                "providerFirstEventMs": _nonnegative_int(completed_attempt.get("firstEventMs")),
                "providerGenerationMs": max(
                    0,
                    _nonnegative_int(completed_attempt.get("durationMs"))
                    - _nonnegative_int(completed_attempt.get("firstByteMs")),
                ),
                "providerRequestBytes": sum(
                    _nonnegative_int(item.get("requestBytes")) for item in provider_attempts
                ),
                "providerResponseBytes": sum(
                    _nonnegative_int(item.get("responseBytes")) for item in provider_attempts
                ),
                "wireMaxOutputTokens": _nonnegative_int(
                    completed_attempt.get("wireMaxOutputTokens")
                ),
                "wireParallelToolCalls": completed_attempt.get("wireParallelToolCalls"),
                "providerAttempts": provider_attempts,
            }
        )

    last_completion_index = completions[-1][0] if completions else -1
    pending_provider_events = [
        (index, event)
        for index, event in enumerate(events)
        if index > last_completion_index and _provider_stream_phase(event)
    ]
    if pending_provider_events:
        first_provider_index = pending_provider_events[0][0]
        pending_start = next(
            (
                (index, event)
                for index, event in reversed(starts)
                if last_completion_index < index < first_provider_index
            ),
            None,
        )
        if pending_start is not None:
            start_index, start = pending_start
            started_at = (
                _payload_timestamp(start, "startedAt")
                or _event_timestamp(start)
                or request_started
            )
        else:
            start_index = first_provider_index
            started_at = _event_timestamp(pending_provider_events[0][1]) or request_started
        terminal_event = next(
            (
                event
                for event in events[first_provider_index:]
                if _event_name(event) in _TERMINAL_EVENTS
            ),
            None,
        )
        finished_at = (
            _event_timestamp(terminal_event)
            if terminal_event is not None
            else _event_timestamp(pending_provider_events[-1][1])
        )
        provider_attempts = _provider_attempt_records(events[start_index:])
        last_attempt = provider_attempts[-1] if provider_attempts else {}
        round_retries = sum(
            1
            for item in events[start_index:]
            if _event_name(item) in {"ConnectionRetry", "ProviderRetry"}
        )
        records.append(
            {
                "round": _nonnegative_int(
                    _value(start, "round") or _value(start, "current")
                )
                if pending_start is not None
                else len(records) + 1,
                "status": "failed",
                "startedAt": _format_timestamp(started_at),
                "firstByteAt": "",
                "completedAt": _format_timestamp(finished_at),
                "timeToFirstByteMs": 0,
                "firstByteSource": "unavailable_after_response_head",
                "durationMs": _duration_ms(started_at, finished_at),
                "toolCalls": 0,
                "retryCount": round_retries,
                "responseModel": "",
                "finishReason": "",
                "nativeReasoning": False,
                "inputTokens": 0,
                "cachedInputTokens": 0,
                "outputTokens": 0,
                "reasoningTokens": 0,
                "providerResponseHeadMs": sum(
                    _nonnegative_int(item.get("responseHeadMs"))
                    for item in provider_attempts
                ),
                "providerFirstByteMs": 0,
                "providerFirstEventMs": 0,
                "providerGenerationMs": 0,
                "providerRequestBytes": sum(
                    _nonnegative_int(item.get("requestBytes")) for item in provider_attempts
                ),
                "providerResponseBytes": sum(
                    _nonnegative_int(item.get("responseBytes")) for item in provider_attempts
                ),
                "wireMaxOutputTokens": _nonnegative_int(
                    last_attempt.get("wireMaxOutputTokens")
                ),
                "wireParallelToolCalls": last_attempt.get("wireParallelToolCalls"),
                "failureHttpStatus": _nonnegative_int(last_attempt.get("httpStatus")),
                "providerAttempts": provider_attempts,
            }
        )
    return records


def _tool_records(events: Sequence[Mapping[str, Any]]) -> list[Dict[str, Any]]:
    starts: dict[str, tuple[int, Mapping[str, Any]]] = {}
    records: list[Dict[str, Any]] = []
    for index, event in enumerate(events):
        name = _event_name(event)
        payload = _event_data(event)
        call_id = str(payload.get("tool_call_id") or payload.get("toolCallId") or "").strip()
        if name in {"ToolStart", "ToolStarted"}:
            if call_id:
                starts[call_id] = (index, event)
            continue
        if name != "ToolDone":
            continue
        start = starts.pop(call_id, None) if call_id else None
        started_at = _event_timestamp(start[1]) if start else None
        completed_at = _event_timestamp(event)
        duration = _nonnegative_int(payload.get("duration_ms") or payload.get("durationMs"))
        if not duration:
            duration = _duration_ms(started_at, completed_at)
        records.append(
            {
                "tool": str(payload.get("tool_name") or payload.get("toolName") or ""),
                "callId": call_id,
                "startedAt": _format_timestamp(started_at),
                "completedAt": _format_timestamp(completed_at),
                "durationMs": duration,
                "error": bool(payload.get("is_error") or payload.get("isError")),
            }
        )
    return records


def _phase_records(events: Sequence[Mapping[str, Any]]) -> list[Dict[str, Any]]:
    active: dict[str, Dict[str, Any]] = {}
    records: list[Dict[str, Any]] = []
    for event in events:
        if _event_name(event) != "TurnPhase":
            continue
        phase = str(_value(event, "phase") or "").strip()
        if not phase:
            continue
        status = str(_value(event, "status") or "").strip().lower()
        event_time = _event_timestamp(event)
        payload_started = _payload_timestamp(event, "startedAt")
        if status == "running":
            current = active.get(phase)
            if current is None:
                active[phase] = {
                    "phase": phase,
                    "label": str(_value(event, "label") or ""),
                    "startedAt": payload_started or event_time,
                }
            continue
        if status not in {"success", "warning", "error", "failed", "cancelled"}:
            continue
        current = active.pop(phase, None)
        started_at = (
            current.get("startedAt") if current else None
        ) or payload_started or event_time
        elapsed = _nonnegative_int(_value(event, "elapsedMs"))
        if not elapsed:
            elapsed = _duration_ms(started_at, event_time)
        records.append(
            {
                "phase": phase,
                "label": str(_value(event, "label") or (current or {}).get("label") or ""),
                "status": status,
                "startedAt": _format_timestamp(started_at),
                "completedAt": _format_timestamp(event_time),
                "durationMs": elapsed,
            }
        )
    return records


def build_agent_lifecycle_trace(
    events: Sequence[Mapping[str, Any]],
    *,
    request_started_at: str = "",
    request_finished_at: str = "",
) -> Dict[str, Any]:
    """Return a redaction-safe lifecycle summary for an Agent turn."""

    normalized = [event for event in events if isinstance(event, Mapping)]
    timestamps = [timestamp for event in normalized if (timestamp := _event_timestamp(event)) is not None]
    started = _parse_timestamp(request_started_at) or (timestamps[0] if timestamps else None)
    finished = _parse_timestamp(request_finished_at) or (timestamps[-1] if timestamps else None)

    raw_first = _first_provider_stream_event(normalized, "first_byte")
    explicit_first = raw_first or _first_event(normalized, {"ProviderFirstByte", "FirstByte"})
    first_output = _first_event(normalized, _OUTPUT_EVENTS)
    first_tool = _first_event(normalized, {"ToolStart", "ToolStarted"})
    first_completed = _first_event(normalized, {"ModelCompleted"})
    first_candidates = [
        candidate
        for candidate in (explicit_first, first_output, first_tool, first_completed)
        if candidate is not None
    ]
    first_byte_item = min(first_candidates, key=lambda item: item[0]) if first_candidates else None
    first_byte_time = _event_timestamp(first_byte_item[1]) if first_byte_item else None
    first_visible = _first_event(normalized, {"TextChunk"})
    first_visible_time = _event_timestamp(first_visible[1]) if first_visible else None
    if finished is None:
        terminal_item = _first_event(normalized, _TERMINAL_EVENTS)
        finished = _event_timestamp(terminal_item[1]) if terminal_item else None

    rounds = _round_records(normalized, started)
    tools = _tool_records(normalized)
    phases = _phase_records(normalized)
    retries: list[Dict[str, Any]] = []
    for index, event in enumerate(normalized):
        if _event_name(event) not in {"ConnectionRetry", "ProviderRetry"}:
            continue
        next_substantive = next(
            (candidate for candidate in normalized[index + 1 :] if _event_name(candidate) in _SUBSTANTIVE_EVENTS),
            None,
        )
        retry_time = _event_timestamp(event)
        recovery_time = _event_timestamp(next_substantive) if next_substantive else None
        payload = _event_data(event)
        retries.append(
            {
                "attempt": _nonnegative_int(payload.get("attempt")),
                "maxAttempts": _nonnegative_int(payload.get("maxAttempts") or payload.get("max_attempts")),
                "at": _format_timestamp(retry_time),
                "recoveredAt": _format_timestamp(recovery_time),
                "recoveryMs": _duration_ms(retry_time, recovery_time),
                "resetTextCharacters": _nonnegative_int(
                    payload.get("resetTextCharacters") or payload.get("reset_text_characters")
                ),
            }
        )

    terminal: Dict[str, Any] = {}
    for event in reversed(normalized):
        name = _event_name(event)
        if name not in _TERMINAL_EVENTS:
            continue
        payload = _event_data(event)
        terminal = {
            "event": name,
            "at": _format_timestamp(_event_timestamp(event)),
            "status": str(payload.get("status") or ""),
            "code": str(payload.get("code") or payload.get("error_type") or ""),
            "reason": str(payload.get("reason") or ""),
        }
        break

    phase_totals: Dict[str, int] = {}
    for phase in phases:
        phase_name = str(phase.get("phase") or "")
        phase_totals[phase_name] = max(
            phase_totals.get(phase_name, 0),
            _nonnegative_int(phase.get("durationMs")),
        )

    source = ""
    first_name = _event_name(first_byte_item[1]) if first_byte_item else ""
    if raw_first is not None and first_byte_item == raw_first:
        source = "provider_raw_stream"
    elif first_name in {"ProviderFirstByte", "FirstByte"}:
        source = "provider_stream"
    elif first_name in {"ReasoningChunk", "TextChunk"}:
        source = "first_output_delta"
    elif first_name in {"ToolStart", "ToolStarted"}:
        source = "tool_call"
    elif first_name == "ModelCompleted":
        source = "model_completed_fallback"
    elif _first_provider_stream_event(normalized, "response_head") is not None:
        source = "unavailable_after_response_head"
    elif normalized:
        source = "unavailable"

    return {
        "_type": _LIFECYCLE_TYPE,
        "_version": _LIFECYCLE_VERSION,
        "clock": "server_event_timestamp" if any(event.get("timestamp") for event in normalized) else "observed_at",
        "requestStartedAt": _format_timestamp(started),
        "firstByteAt": _format_timestamp(first_byte_time),
        "firstByteSource": source,
        "firstVisibleOutputAt": _format_timestamp(first_visible_time),
        "completedAt": _format_timestamp(finished),
        "timeToFirstByteMs": _duration_ms(started, first_byte_time),
        "timeToFirstVisibleOutputMs": _duration_ms(started, first_visible_time),
        "durationMs": _duration_ms(started, finished),
        "providerWaitMs": sum(
            _nonnegative_int(round_item.get("providerFirstByteMs"))
            or _nonnegative_int(round_item.get("providerResponseHeadMs"))
            or _nonnegative_int(round_item.get("timeToFirstByteMs"))
            for round_item in rounds
        ),
        "providerResponseHeadMs": sum(
            _nonnegative_int(round_item.get("providerResponseHeadMs")) for round_item in rounds
        ),
        "providerFirstByteMs": sum(
            _nonnegative_int(round_item.get("providerFirstByteMs")) for round_item in rounds
        ),
        "providerGenerationMs": sum(
            _nonnegative_int(round_item.get("providerGenerationMs")) for round_item in rounds
        ),
        "providerRequestBytes": sum(
            _nonnegative_int(round_item.get("providerRequestBytes")) for round_item in rounds
        ),
        "providerResponseBytes": sum(
            _nonnegative_int(round_item.get("providerResponseBytes")) for round_item in rounds
        ),
        "modelGenerationMs": sum(_nonnegative_int(round_item.get("durationMs")) for round_item in rounds),
        "toolExecutionMs": sum(_nonnegative_int(tool.get("durationMs")) for tool in tools),
        "modelRounds": len(rounds),
        "completedModelRounds": sum(
            1 for round_item in rounds if round_item.get("status") == "completed"
        ),
        "failedModelRounds": sum(
            1 for round_item in rounds if round_item.get("status") == "failed"
        ),
        "toolCalls": len(tools),
        "retryCount": len(retries),
        "retryRecoveryMs": sum(_nonnegative_int(item.get("recoveryMs")) for item in retries),
        "visibleOutputChars": sum(
            _nonnegative_int(_value(event, "visibleChars"))
            or len(str(_value(event, "content") or ""))
            for event in normalized
            if _event_name(event) == "TextChunk"
        ),
        "rounds": rounds,
        "tools": tools,
        "retries": retries,
        "phases": phases,
        "phaseTotalsMs": phase_totals,
        "terminal": terminal,
    }


__all__ = ["build_agent_lifecycle_trace"]
